### ISSUE TITLE
Valid but useless beam definition causes a test to fail

### ISSUE THREAD

**Issue by zmitchell** [zmitchell/polsim#2]
If you define a useless yet valid beam as follows

```toml
[beam]
polarization = "elliptical"
x_mag = 0
y_mag = 0
x_phase = 0
y_phase = 0
angle_units = "degrees"
```

it will trigger the following test failure:

```
---- validate::test::test_validate_elliptical_pol_rejects_invalid_def stdout ----
thread 'validate::test::test_validate_elliptical_pol_rejects_invalid_def' panicked at 'Test failed: assertion failed: validate_elliptical_pol(&def).is_err() at src\validate.rs:584; minimal failing input: def = BeamDef { polarization: Elliptical, angle: None, angle_units: None, x_mag: Some(-0.0), x_phase: Some(0.0), y_mag: Some(0.0), y_phase: Some(0.0), phase_units: Some(Degrees), handedness: None }
	successes: 134
	local rejects: 201
		201 times at float is not well-behaved
	global rejects: 0
', src\validate.rs:516:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
